### ISSUE TITLE
Calibration and data times not quite matching 

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_cal#204] opened 2018-03-07 03:39 UTC
When developing smooth_cal, I built a function that checked the consistency of the data sets and calibration files that were loaded in.

One check I could not pass is the commented one here:
https://github.com/HERA-Team/hera_cal/blob/2cb03130577df697cfdc1537b19448600f48d7d1/hera_cal/smooth_cal.py#L176

Basically, I'm finding that the times in calfits files and the times in miriad files that are supposedly the same JD are not quite the same. 

Running `print sc.times - sc.data_times` after https://github.com/HERA-Team/hera_cal/blob/2cb03130577df697cfdc1537b19448600f48d7d1/scripts/notebooks/running_smooth_cal.ipynb
yields (in days):

```
[  0.00000000e+00   4.19095159e-09   8.84756446e-09   1.30385160e-08
   1.72294676e-08   2.14204192e-08   2.60770321e-08   3.02679837e-08
   3.44589353e-08   3.86498868e-08   4.37721610e-08   4.79631126e-08
   5.21540642e-08   5.63450158e-08   6.10016286e-08   6.51925802e-08
   6.93835318e-08   7.40401447e-08   7.82310963e-08   8.24220479e-08
   8.66129994e-08   9.12696123e-08   9.54605639e-08   9.96515155e-08
   1.03842467e-07   1.08499080e-07   1.12690032e-07   1.16880983e-07
   1.21071935e-07   1.25728548e-07   1.29919499e-07   1.34110451e-07
   1.38767064e-07   1.42958015e-07   1.47148967e-07   1.51339918e-07
   1.55996531e-07   1.60187483e-07   1.64378434e-07   1.68569386e-07
   1.73225999e-07   1.77416950e-07   1.81607902e-07   1.86264515e-07
   1.90455467e-07   1.94646418e-07   1.98837370e-07   2.03493983e-07
   2.07684934e-07   2.11875886e-07   2.16066837e-07   2.20723450e-07
   2.24914402e-07   2.29105353e-07   2.33296305e-07   2.37952918e-07
   2.42609531e-07   2.46800482e-07   2.51457095e-07   2.55648047e-07]
```

They start in agreement but the disagreement grows linearly at about 0.00037437 s per integration.

Any thoughts on what's going on here? @zakiali @adampbeardsley @dannyjacobs @plaplant @nkern ?

**Comment by adampbeardsley** [comment] 2018-03-07 15:16
My first thought is that the time arrays may be built up instead of stored/copied exactly. So if the cal routine producing the cal object to start just uses the delta-t, it's possible there is a floating point-level disagreement. Or, even if the time array is copied directly, it's possible calfits read/write uses the delta to reconstruct.
I can look at these ideas in more detail later today, but I thought I'd post my thoughts in case anyone else wants to start hunting in the mean time.

**Comment by adampbeardsley** [comment] 2018-03-07 17:16
A little update... calfits indeed uses a delta to store the time info. 
And it looks like it has some bugs in the way it's doing it (see HERA-Team/pyuvdata#311). I was able to reproduce the error Josh sees directly using the time array from the data file. So I'm on to something.
Will report back once I close the pyuvdata issue.

**Comment by jsdillon** [comment] 2018-03-07 18:35
Thanks for tracking it down, Adam.

**Comment by adampbeardsley** [comment] 2018-03-07 20:54
Ok, so pyuvdata is now fixed. Unfortunately, this does not fix the files that are already written with incorrect data. So I don't know if you want to change the testing calfits files, or change the tolerance of the check. Any calfits files that were written before this fix will have the problem, so everything the RTP has done so far.

**Closed** 2018-06-04 22:52 UTC
